/**
 * Common English words and names used for dictionary-aware password strength
 * scoring. When a password is composed of these words, we estimate entropy
 * per-word (log2 of dictionary size) rather than per-character, which gives
 * a much more realistic strength estimate.
 */

// Lazily initialized; split on first access
let _wordSet: Set<string> | null = null;

const W = (...chunks: string[]) => chunks.join(" ");

const WORDS = W(
	// Function words, pronouns, prepositions, conjunctions
	"a about above across after again against ago ahead all almost along already also always am among",
	"an and another any anybody anyone anything are around as at away back be because been before",
	"behind being below beneath beside besides between beyond both but by can could did do does done",
	"down during each either else enough even ever every everybody everyone everything except few for",
	"from get got had has have he her here hers herself him himself his how however i if in inside",
	"into is it its itself just least less let like may me might mine more most much must my myself",
	"near neither never no nobody none nor not nothing now of off often on once one only onto or other",
	"others otherwise our ours ourselves out outside over own past per perhaps quite rather really",
	"round same several shall she should since so some somebody someone something sometimes still such",
	"than that the their theirs them themselves then there therefore these they this thorough those",
	"though through throughout till to together too toward towards under unless until up upon us very",
	"was we well were what whatever when whenever where wherever whether which while who whoever whom",
	"whose why will with within without would yet you your yours yourself yourselves",

	// Common verbs
	"accept achieve act add admit affect afford agree aim allow appear apply arrive ask assume attack",
	"avoid base beat become begin believe belong break bring build burn buy call care carry catch cause",
	"change charge check choose claim climb close collect come commit compare complain complete concern",
	"confirm connect consider contain continue contribute control cook copy correct cost count cover",
	"create cross cry cut damage dance deal decide deliver demand deny depend describe design destroy",
	"develop die disappear discover discuss divide doubt drag draw dream dress drink drive drop dry eat",
	"employ encourage enjoy examine exist expect experience explain express extend face fail fall fancy",
	"feed feel fight fill find finish fit fly fold follow force forget forgive form found gain gather",
	"generate give go grant grow guess handle hang happen hate head hear help hide hit hold hope hurt",
	"identify imagine improve include increase indicate influence inform insist intend introduce invest",
	"involve issue join judge jump keep kick kill knock know lack last laugh launch lay lead learn leave",
	"lend lie lift like limit link listen live look lose love maintain make manage mark matter mean meet",
	"mention mind miss mix monitor move murder must name need note notice obtain occur offer open operate",
	"order organize ought own paint pass pay perform permit pick place plan plant play point pour prefer",
	"prepare present press prevent produce promise promote protect prove provide publish pull push put",
	"question raise reach read realize receive recognize recommend record reduce refer reflect refuse",
	"regard relate release remain remember remind remove repeat replace report represent request require",
	"respond rest result retain return reveal ring rise roll run rush save say score search see seek seem",
	"sell send separate serve set settle shake shape share shoot should show shut sign sing sit sleep slip",
	"smile sort sound speak spend spread stand start state stay step stick stop stretch strike study stuff",
	"submit succeed suffer suggest suit supply support suppose survive swim take talk taste teach tell",
	"tend test thank think throw tie touch train travel treat try turn understand use used visit vote",
	"wait wake walk want warn wash watch wave wear weigh welcome win wish wonder work worry write",

	// Common nouns
	"accident account address advantage afternoon age agency agent agreement air amount angle animal",
	"answer apartment appeal appearance apple application area argument army arrival art article attack",
	"attempt attention audience author baby back bag balance ball band bank bar base basis basket bath",
	"bathroom battle beach bear beat bed bedroom beer bell bird bit bite block blood blow board boat body",
	"bomb bone book border boss bottle bottom box boy brain branch bread break breakfast breath brick",
	"bridge brother budget building bus bush business butter button cabinet cake call camera camp",
	"campaign cancer candidate capital car card career carpet case cash cat catch category cause cell",
	"center chair chairman challenge champion chance change channel chapter character charge chart check",
	"cheek cheese chest chicken chief child chip chocolate choice church cigarette circle circumstance",
	"city claim class classroom client climate clock clothes cloud club clue coach coal coast code coffee",
	"cold collar collection college color column combination command comment commission committee common",
	"communication community company comparison competition complaint computer concept concern condition",
	"conference confidence conflict congress connection consequence contact content contest context",
	"contract contribution control conversation cook cookie copy corner cost count counter country",
	"county couple courage course court cousin cover crash cream crime crisis criticism cross crowd cry",
	"culture cup currency current customer cut cycle dad damage dance danger data database date daughter",
	"day dead deal death debate decade decision deep definition degree demand department departure depth",
	"description desert design designer desk detail development device diet difference difficulty dinner",
	"direction director dirt disaster discipline discount discussion disease dish disk display distance",
	"district doctor document dog dollar door double doubt draft drama draw drawing dream dress drink",
	"driver drop drug dust duty ear earth ease east edge education effect effort egg eight election",
	"element emergency emotion emphasis empire employee employer employment energy engine engineer",
	"entertainment entry environment episode equal equipment era error escape essay estate evening event",
	"evidence exam examination example exchange excitement exercise exhibition existence expansion",
	"experience expert explanation expression extension extent extreme eye face fact factor failure faith",
	"fall family fan farm farmer fat father fault fear feature fee feeling female fence few fiction field",
	"fight figure file film final finance finding finger fire firm fish flight floor flower fly focus",
	"folk food foot football force forest forever form formal foundation frame freedom friend front fruit",
	"fuel fun function fund future gain game gap garage garden gas gate general generation gift girl",
	"girlfriend glad glass global goal god gold golf good government governor grade grain grandfather",
	"grandmother grass great green ground group growth guard guess guest guide guitar gun guy habit hair",
	"half hall hand handle hang harm hat hate head health hearing heart heat height hell hello help hero",
	"highway hill history hit hole holiday home honey hope horror horse hospital host hotel hour house",
	"housing human humor hundred hunt husband ice idea image imagination impact importance impression",
	"incident income increase independence indication individual industry inflation influence",
	"information initial initiative injury inside inspection instance instruction insurance intention",
	"interest internet introduction investment investor iron island issue item jacket job joint joke",
	"journal journey joy judge judgment juice jump junior jury justice key kid king kingdom kiss kitchen",
	"knee knife knowledge lab label lack lady lake land landscape language lab laptop law lawyer leader",
	"leadership league leather leave left leg length lesson letter level library lie life lifestyle lift",
	"light limit line link lip list literature living load loan location lock log long look lord loss lot",
	"love luck lunch machine magazine mail main maintenance major male mall man management manager manner",
	"manufacturer map march mark market marriage master match material math matter meal meaning measure",
	"measurement meat mechanism media medicine meeting member membership memory mention menu mess message",
	"metal method middle might mile milk mind mine minister minor minute mirror mission mistake mix",
	"mixture model mom moment money monitor month mood moon morning mortgage mother motor mountain mouse",
	"mouth move movement movie mud murder muscle museum music mystery nail name narrative nation natural",
	"nature neck negotiation neighbor nerve net network news newspaper night nobody noise normal north",
	"nose note nothing notice novel number nurse object objective obligation observation occasion offer",
	"office officer official oil opening operation opinion opponent opportunity opposite option orange",
	"order ordinary organization original other outcome output outside oven owner package page pain paint",
	"painting pair palace pan panel paper parent park parking part partner passenger past path patience",
	"patient pattern pause payment peace peak pen penalty pension people percent percentage perception",
	"performance period permission permit person personality perspective phase philosophy phone photo",
	"phrase physical piano picture pie piece pilot pin pipe pitch pizza place plan plane plant plastic",
	"plate platform player please pleasure plenty pocket poem poet poetry point pole police policy",
	"political politics pollution pool poor pop population porch port portion position positive",
	"possession possibility post potato pound pour poverty power practice prayer preference preparation",
	"presence president pressure price pride priest primary prince princess principle print priority",
	"prison prisoner privacy private prize problem procedure process produce product production",
	"profession professional professor profit program progress project promise promotion proof proposal",
	"protection protein protest public pull punch purpose push quality quarter queen question quiet quote",
	"race radio rain range rate ratio reaction reader reading reality reason recipe record recording red",
	"reference reflection reform region regular relation relationship release religion remote repeat",
	"replacement report reporter republic reputation request requirement research resident resistance",
	"resolution resource respect response responsibility rest restaurant result return revenue review",
	"revolution rhythm rice ride ring risk river road rock role roof room root rope round route row rule",
	"run rush safe safety sake salad salary sale salt sample sand savings scale scene schedule scheme",
	"scholar scholarship school science scientist score screen sea search season seat second secret",
	"secretary section sector security selection self senate senator senior sense sensitive sentence",
	"sequence series seriously servant service session setting seven sex sexual shadow shake shape share",
	"she sheet shelf shell shift ship shirt shock shoe shoot shooting shop shopping shore shot shoulder",
	"show shower side sight sign signal significance silence silver simple singer sir sister site",
	"situation six size skill skin sky slave sleep slice slip smell smile smoke snow social society",
	"software soil soldier solution somebody somewhere son song sort soul sound source south southern",
	"space speaker special specialist specific speech speed spend spirit spiritual sport spot spring",
	"square stable staff stage stair stake stand standard standing star start state statement station",
	"status stay steady steam steel step stick still stock stomach stone stop storage store storm story",
	"stranger strategy stream street strength stress stretch strike string strip stroke structure",
	"struggle student studio study stuff style subject success sugar suit summer sun supply support",
	"surface surprise survey suspect sweet swim switch symbol system table tail tale talent tank tape",
	"target task tax tea teacher teaching team tear technology television temperature ten tend tennis",
	"tension term territory terror test text thanks theme theory thing thinking thought thousand threat",
	"throat ticket tie till time tiny tip title today toe tomorrow tone tongue tonight tool top topic",
	"total touch tough tour tourist tower town track trade tradition traffic train training transfer",
	"travel treasure treat treatment tree trial trick trip troop trouble truck trust truth turn twelve",
	"twenty two type uncle under union unique unit universe university upper usage valley value variety",
	"vehicle version victim victory video view village violence virtue vision visit visitor visual voice",
	"volume volunteer vote wage wait walk wall war warning wash waste watch water wave way weakness",
	"wealth weapon weather web website wedding week weekend weight welcome west western wheel whereaswife",
	"will wind window wine wing winner winter wire wish witness woman wonder wood word worker world worry",
	"worth writer writing wrong yard yeah year yellow yes yesterday yet young youth zero zone",

	// Common adjectives
	"able absolute academic acceptable accurate actual additional afraid aggressive ago alive alone",
	"alternative amazing angry annual anxious any apparent appropriate automatic available average aware",
	"awful bad basic beautiful big bitter black blue bold boring born brave brief bright brilliant broad",
	"broken brown busy calm capable careful casual certain cheap cheerful chief civil classic clean clear",
	"clever close cold comfortable commercial common competitive complex comprehensive confident",
	"conscious conservative considerable consistent constant content conventional cool correct costly",
	"crazy creative criminal critical crucial cruel cultural curious current cute daily dangerous dark",
	"dead dear decent deep defensive deliberate delicate dependent deputy desperate different difficult",
	"dirty distinct double dramatic dry due dull eager early eastern easy educational effective efficient",
	"elderly electrical electronic elegant embarrassed emotional empty endless enormous entire",
	"environmental equal essential eternal even eventually every evil exact excellent exciting existing",
	"expensive extensive external extra extraordinary extreme faint fair familiar famous fancy fantastic",
	"far fast fat fatal favorite federal female fewer final financial fine firm first fit flat flexible",
	"following fond foreign formal former fortunate forward free frequent fresh friendly front frozen",
	"full funny future general generous gentle genuine glad global golden good grand grateful gray great",
	"green gross guilty happy hard healthy heavy helpful hidden high historical hollow holy honest",
	"horrible hot huge human hungry ideal ill illegal immediate important impossible impressive",
	"incredible independent individual inevitable informal initial inner innocent intelligent intense",
	"interesting internal international joint junior keen kind known large last late latter leading lean",
	"left legal legitimate less likely limited little live lively local logical lonely long loose lost",
	"loud lovely low lucky mad magic main major male massive material maximum mean medical medium mental",
	"mere middle military minimum minor missing mixed modern modest monthly moral naked narrow nasty",
	"national natural neat necessary negative nervous new next nice no normal northern novel nuclear",
	"numerous obvious odd official old only open opposite orange ordinary original other outdoor outer",
	"overall own painful pale particular passive past patient perfect permanent personal physical plain",
	"plastic pleasant plenty political poor popular positive possible potential powerful practical",
	"pregnant present previous primary prime prior private professional proper proud psychological",
	"public pure purple quick quiet radical random rapid rare raw ready real realistic reasonable recent",
	"red regional regular related relative relevant religious reluctant remaining remote representative",
	"resident responsible rich ridiculous right rough round royal rude rural russian sad safe satisfied",
	"scared secret secure select senior sensitive separate serious severe sexual sharp short shy sick",
	"significant silly similar simple single slight slow small smart smooth so social soft solid some",
	"sorry southern spare special specific spiritual square stable standard static steady strange strict",
	"strong stupid subsequent substantial successful sudden sufficient suitable super surprised",
	"suspicious sweet tall temporary terrible thick thin tiny top total tough traditional tremendous",
	"tropical true typical ugly unable unfair unfortunate unhappy unique united unlikely unusual upper",
	"upset urban useful usual valid valuable various vast violent visible visual vital warm weak wealthy",
	"weird welcome western white whole wide wild willing wise wonderful wooden working worth wrong young",

	// Common first names (male)
	"aaron adam alan albert alex alexander andrew anthony arthur benjamin bill bob brandon brian bruce",
	"carl charles chris christopher craig dale dan daniel dave david dean dennis derek donald douglas",
	"duke dylan earl eddie edward eric eugene frank fred gary george gerald glen gordon grant greg",
	"gregory harold harry henry howard jack jacob jake james jason jay jeff jeffrey jeremy jerry jesse",
	"jim jimmy joe john johnny jonathan jordan jose joseph josh joshua juan justin karl keith ken",
	"kenneth kevin kyle lance larry lee leon leonard lewis lloyd louis luke marcus mark martin matthew",
	"max michael mike mitchell nathan neil nicholas nick noah norman oscar patrick paul peter philip",
	"ralph randy raymond richard robert roger ronald ross roy russell ryan sam samuel scott sean shane",
	"simon stanley stephen steve steven stuart terry theodore thomas tim timothy todd tom tommy tony",
	"travis tyler victor vincent walter warren wayne wesley william zachary",

	// Common first names (female)
	"alice amanda amber amy andrea angela anna anne ashley barbara betty brenda carol caroline",
	"catherine charlotte cheryl christina christine cindy claire crystal cynthia dana dawn deborah",
	"debra denise diana diane donna dorothy eileen elaine elizabeth emily emma eva frances gail gloria",
	"grace heather helen irene jacqueline jane janet janice jean jennifer jessica joan joanne josephine",
	"joyce judith judy julia julie karen katherine kathleen kathryn kathy kelly kimberly laura lauren",
	"linda lisa lori lynn margaret maria marie marilyn martha mary maureen megan melissa michelle monica",
	"nancy natalie nicole norma olivia pamela patricia phyllis rachel rebecca renee robin rose ruth",
	"sally samantha sandra sara sarah sharon shirley sophia stephanie susan tammy teresa theresa tina",
	"tracy vanessa victoria virginia wendy",

	// Common surnames
	"adams allen anderson bailey baker bell bennett brooks brown campbell carter clark cole collins cook",
	"cooper cox cruz davis diaz edwards ellis evans fisher flores foster garcia gonzalez gray green",
	"griffin hall hamilton harris hayes henderson hernandez hill howard hughes hunt jackson james jenkins",
	"johnson jones jordan kelly kim king lee lewis long lopez marshall martin martinez miller mitchell",
	"moore morgan morris murphy murray nelson nguyen ortiz parker patterson perez perry peterson",
	"phillips powell price ramirez reed reynolds richardson rivera roberts robinson rodriguez rogers",
	"ross russell ryan sanchez sanders scott simmons smith stewart sullivan taylor thomas thompson",
	"torres turner walker wallace ward washington watson webb wells west white williams wilson wood",
	"woods wright young",

	// Common password words / tech terms
	"password admin login qwerty monkey dragon master welcome letmein shadow sunshine princess",
	"football baseball soccer hockey batman superman access charlie ninja mustang starwars computer",
	"internet gamer secret trustno iloveyou",

	// Additional common words to fill gaps
	"battery staple blanket candle carpet castle cattle cattle center channel classic column comfort",
	"compare compete connect correct crystal curtain cushion dentist diamond dinosaur dolphin donkey",
	"dragon elephant emerald empire engine envelope factory falcon feather fiction finger flower folder",
	"fountain galaxy giraffe glitter gorilla granite gravel hammer harvest helmet horizon hurricane",
	"insect jacket jasmine journey jungle kangaroo lantern leather leopard library lightning lizard",
	"lobster luggage magnet marble meadow mirror missile monster morning mustard napkin needle neutral",
	"octopus organic package panda panther parrot passage pattern peacock pelican penguin pepper",
	"perfume phantom picture pillow pioneer planet plaster platinum poison pumpkin puppet puzzle rabbit",
	"raccoon rainbow random reptile ribbon rocket saddle salmon sandwich satellite sausage scissors",
	"shelter shrimp silver skeleton soldier sparrow spider sponge stadium station stomach strawberry",
	"struggle student subway sunrise sunset surface surgeon syllable temple tennis terminal theater",
	"thunder tiger tissue tomato tornado tortoise tourist tractor trailer treasure triangle trophy",
	"trumpet tunnel turkey umbrella uniform vampire vanilla velvet venture village vintage violin",
	"volcano voyage walnut warrior whistle window witness wizard wooden yellow zebra",
);

export function getCommonWords(): Set<string> {
	if (_wordSet) return _wordSet;
	_wordSet = new Set(WORDS.split(/\s+/).filter(Boolean));
	return _wordSet;
}
